# Generated by Django 5.0 on 2024-02-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'player',
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
            options={
                'verbose_name_plural': 'score',
                'ordering': ['score'],
            },
        ),
    ]
