# Generated by Django 5.0 on 2024-02-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score'], 'verbose_name_plural': 'score'},
        ),
    ]
